/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'closeRate' : number,
  'averageAssignmentFee' : number,
  'dealConversionPercent' : number,
  'monthlyRevenue' : bigint,
  'leadToContractPercent' : number,
  'profitByZipCode' : Array<[string, bigint]>,
}
export interface Buyer {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'notes' : string,
  'propertyTypePreference' : string,
  'phone' : string,
  'budgetMax' : bigint,
  'budgetMin' : bigint,
  'preferredAreas' : Array<string>,
}
export interface ComparableSale {
  'distance' : number,
  'soldPrice' : bigint,
  'address' : string,
  'soldDate' : bigint,
}
export interface ContractDocument {
  'id' : bigint,
  'emd' : [] | [bigint],
  'documentType' : { 'PurchaseContract' : null } |
    { 'AssignmentContract' : null },
  'owner' : Principal,
  'blob' : ExternalBlob,
  'fileName' : string,
  'dealId' : bigint,
  'closingDate' : [] | [bigint],
  'signingStatus' : { 'Unsigned' : null } |
    { 'Signed' : null },
  'uploadedAt' : bigint,
}
export interface Deal {
  'id' : bigint,
  'arv' : bigint,
  'contractDeadline' : [] | [bigint],
  'sellerPhone' : string,
  'owner' : Principal,
  'askingPrice' : bigint,
  'createdAt' : bigint,
  'actualProfit' : [] | [bigint],
  'sellerName' : string,
  'updatedAt' : bigint,
  'stage' : DealStage,
  'address' : string,
  'notes' : string,
  'repairs' : bigint,
  'yourOffer' : bigint,
  'estimatedProfit' : bigint,
  'assignedBuyer' : [] | [bigint],
}
export interface DealAnalysis {
  'suggestedOfferPrice' : bigint,
  'estimatedARV' : bigint,
  'estimatedMAO' : bigint,
  'lastSoldPrice' : [] | [bigint],
  'estimatedAssignmentFee' : bigint,
  'dealRating' : { 'A' : null } |
    { 'B' : null } |
    { 'C' : null } |
    { 'Risky' : null },
  'address' : string,
  'comparableSales' : Array<ComparableSale>,
  'estimatedRehabCost' : bigint,
}
export type DealStage = { 'Closed' : null } |
  { 'ContactedSeller' : null } |
  { 'UnderContract' : null } |
  { 'NewLead' : null } |
  { 'Negotiating' : null } |
  { 'Assigned' : null };
export type ExternalBlob = Uint8Array;
export interface MembershipCatalog {
  'pro' : MembershipPricing,
  'enterprise' : MembershipPricing,
  'lastUpdated' : bigint,
  'basic' : MembershipPricing,
}
export interface MembershipPricing {
  'annualPriceCents' : bigint,
  'monthlyPriceCents' : bigint,
  'salePriceCents' : [] | [bigint],
  'isOnSale' : boolean,
}
export type MembershipTier = { 'Pro' : null } |
  { 'Enterprise' : null } |
  { 'Basic' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
  'membershipTier' : MembershipTier,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeDeal' : ActorMethod<[string], DealAnalysis>,
  'assignBuyerToDeal' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBuyer' : ActorMethod<
    [string, string, string, Array<string>, bigint, bigint, string, string],
    bigint
  >,
  'createDeal' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, bigint, string, bigint],
    bigint
  >,
  'createDealFromAnalysis' : ActorMethod<
    [DealAnalysis, string, string],
    bigint
  >,
  'deleteBuyer' : ActorMethod<[bigint], undefined>,
  'deleteDeal' : ActorMethod<[bigint], undefined>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getBuyer' : ActorMethod<[bigint], [] | [Buyer]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContract' : ActorMethod<[bigint], [] | [ContractDocument]>,
  'getDeal' : ActorMethod<[bigint], [] | [Deal]>,
  'getMembershipCatalog' : ActorMethod<[], [] | [MembershipCatalog]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBuyers' : ActorMethod<[], Array<Buyer>>,
  'listContractsByDeal' : ActorMethod<[bigint], Array<ContractDocument>>,
  'listDeals' : ActorMethod<[], Array<Deal>>,
  'moveDealToStage' : ActorMethod<[bigint, DealStage], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBuyer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<string>,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'updateContractStatus' : ActorMethod<
    [
      bigint,
      { 'Unsigned' : null } |
        { 'Signed' : null },
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'updateDeal' : ActorMethod<
    [
      bigint,
      DealStage,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      [] | [bigint],
      [] | [bigint],
      string,
      bigint,
      [] | [bigint],
    ],
    undefined
  >,
  'updateMembershipPricing' : ActorMethod<
    [MembershipPricing, MembershipPricing, MembershipPricing],
    undefined
  >,
  'updateMembershipTier' : ActorMethod<[Principal, MembershipTier], undefined>,
  'uploadContract' : ActorMethod<
    [
      bigint,
      { 'PurchaseContract' : null } |
        { 'AssignmentContract' : null },
      string,
      [] | [bigint],
      [] | [bigint],
      ExternalBlob,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];