/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ComparableSale = IDL.Record({
  'distance' : IDL.Float64,
  'soldPrice' : IDL.Nat,
  'address' : IDL.Text,
  'soldDate' : IDL.Int,
});
export const DealAnalysis = IDL.Record({
  'suggestedOfferPrice' : IDL.Nat,
  'estimatedARV' : IDL.Nat,
  'estimatedMAO' : IDL.Nat,
  'lastSoldPrice' : IDL.Opt(IDL.Nat),
  'estimatedAssignmentFee' : IDL.Nat,
  'dealRating' : IDL.Variant({
    'A' : IDL.Null,
    'B' : IDL.Null,
    'C' : IDL.Null,
    'Risky' : IDL.Null,
  }),
  'address' : IDL.Text,
  'comparableSales' : IDL.Vec(ComparableSale),
  'estimatedRehabCost' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalyticsData = IDL.Record({
  'closeRate' : IDL.Float64,
  'averageAssignmentFee' : IDL.Float64,
  'dealConversionPercent' : IDL.Float64,
  'monthlyRevenue' : IDL.Nat,
  'leadToContractPercent' : IDL.Float64,
  'profitByZipCode' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const Buyer = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'propertyTypePreference' : IDL.Text,
  'phone' : IDL.Text,
  'budgetMax' : IDL.Nat,
  'budgetMin' : IDL.Nat,
  'preferredAreas' : IDL.Vec(IDL.Text),
});
export const MembershipTier = IDL.Variant({
  'Pro' : IDL.Null,
  'Enterprise' : IDL.Null,
  'Basic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'membershipTier' : MembershipTier,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContractDocument = IDL.Record({
  'id' : IDL.Nat,
  'emd' : IDL.Opt(IDL.Nat),
  'documentType' : IDL.Variant({
    'PurchaseContract' : IDL.Null,
    'AssignmentContract' : IDL.Null,
  }),
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'dealId' : IDL.Nat,
  'closingDate' : IDL.Opt(IDL.Int),
  'signingStatus' : IDL.Variant({ 'Unsigned' : IDL.Null, 'Signed' : IDL.Null }),
  'uploadedAt' : IDL.Int,
});
export const DealStage = IDL.Variant({
  'Closed' : IDL.Null,
  'ContactedSeller' : IDL.Null,
  'UnderContract' : IDL.Null,
  'NewLead' : IDL.Null,
  'Negotiating' : IDL.Null,
  'Assigned' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'arv' : IDL.Nat,
  'contractDeadline' : IDL.Opt(IDL.Int),
  'sellerPhone' : IDL.Text,
  'owner' : IDL.Principal,
  'askingPrice' : IDL.Nat,
  'createdAt' : IDL.Int,
  'actualProfit' : IDL.Opt(IDL.Nat),
  'sellerName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'stage' : DealStage,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'repairs' : IDL.Nat,
  'yourOffer' : IDL.Nat,
  'estimatedProfit' : IDL.Nat,
  'assignedBuyer' : IDL.Opt(IDL.Nat),
});
export const MembershipPricing = IDL.Record({
  'annualPriceCents' : IDL.Nat,
  'monthlyPriceCents' : IDL.Nat,
  'salePriceCents' : IDL.Opt(IDL.Nat),
  'isOnSale' : IDL.Bool,
});
export const MembershipCatalog = IDL.Record({
  'pro' : MembershipPricing,
  'enterprise' : MembershipPricing,
  'lastUpdated' : IDL.Int,
  'basic' : MembershipPricing,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeDeal' : IDL.Func([IDL.Text], [DealAnalysis], []),
  'assignBuyerToDeal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBuyer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createDeal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createDealFromAnalysis' : IDL.Func(
      [DealAnalysis, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBuyer' : IDL.Func([IDL.Nat], [], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [], []),
  'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getBuyer' : IDL.Func([IDL.Nat], [IDL.Opt(Buyer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(ContractDocument)], ['query']),
  'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
  'getMembershipCatalog' : IDL.Func([], [MembershipCatalog], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBuyers' : IDL.Func([], [IDL.Vec(Buyer)], ['query']),
  'listContractsByDeal' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ContractDocument)],
      ['query'],
    ),
  'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'moveDealToStage' : IDL.Func([IDL.Nat, DealStage], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBuyer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateContractStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({ 'Unsigned' : IDL.Null, 'Signed' : IDL.Null }),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateDeal' : IDL.Func(
      [
        IDL.Nat,
        DealStage,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateMembershipPricing' : IDL.Func(
      [MembershipPricing, MembershipPricing, MembershipPricing],
      [],
      [],
    ),
  'updateMembershipTier' : IDL.Func([IDL.Principal, MembershipTier], [], []),
  'uploadContract' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'PurchaseContract' : IDL.Null,
          'AssignmentContract' : IDL.Null,
        }),
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
        ExternalBlob,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ComparableSale = IDL.Record({
    'distance' : IDL.Float64,
    'soldPrice' : IDL.Nat,
    'address' : IDL.Text,
    'soldDate' : IDL.Int,
  });
  const DealAnalysis = IDL.Record({
    'suggestedOfferPrice' : IDL.Nat,
    'estimatedARV' : IDL.Nat,
    'estimatedMAO' : IDL.Nat,
    'lastSoldPrice' : IDL.Opt(IDL.Nat),
    'estimatedAssignmentFee' : IDL.Nat,
    'dealRating' : IDL.Variant({
      'A' : IDL.Null,
      'B' : IDL.Null,
      'C' : IDL.Null,
      'Risky' : IDL.Null,
    }),
    'address' : IDL.Text,
    'comparableSales' : IDL.Vec(ComparableSale),
    'estimatedRehabCost' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalyticsData = IDL.Record({
    'closeRate' : IDL.Float64,
    'averageAssignmentFee' : IDL.Float64,
    'dealConversionPercent' : IDL.Float64,
    'monthlyRevenue' : IDL.Nat,
    'leadToContractPercent' : IDL.Float64,
    'profitByZipCode' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const Buyer = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'propertyTypePreference' : IDL.Text,
    'phone' : IDL.Text,
    'budgetMax' : IDL.Nat,
    'budgetMin' : IDL.Nat,
    'preferredAreas' : IDL.Vec(IDL.Text),
  });
  const MembershipTier = IDL.Variant({
    'Pro' : IDL.Null,
    'Enterprise' : IDL.Null,
    'Basic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'membershipTier' : MembershipTier,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContractDocument = IDL.Record({
    'id' : IDL.Nat,
    'emd' : IDL.Opt(IDL.Nat),
    'documentType' : IDL.Variant({
      'PurchaseContract' : IDL.Null,
      'AssignmentContract' : IDL.Null,
    }),
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'dealId' : IDL.Nat,
    'closingDate' : IDL.Opt(IDL.Int),
    'signingStatus' : IDL.Variant({
      'Unsigned' : IDL.Null,
      'Signed' : IDL.Null,
    }),
    'uploadedAt' : IDL.Int,
  });
  const DealStage = IDL.Variant({
    'Closed' : IDL.Null,
    'ContactedSeller' : IDL.Null,
    'UnderContract' : IDL.Null,
    'NewLead' : IDL.Null,
    'Negotiating' : IDL.Null,
    'Assigned' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'arv' : IDL.Nat,
    'contractDeadline' : IDL.Opt(IDL.Int),
    'sellerPhone' : IDL.Text,
    'owner' : IDL.Principal,
    'askingPrice' : IDL.Nat,
    'createdAt' : IDL.Int,
    'actualProfit' : IDL.Opt(IDL.Nat),
    'sellerName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'stage' : DealStage,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'repairs' : IDL.Nat,
    'yourOffer' : IDL.Nat,
    'estimatedProfit' : IDL.Nat,
    'assignedBuyer' : IDL.Opt(IDL.Nat),
  });
  const MembershipPricing = IDL.Record({
    'annualPriceCents' : IDL.Nat,
    'monthlyPriceCents' : IDL.Nat,
    'salePriceCents' : IDL.Opt(IDL.Nat),
    'isOnSale' : IDL.Bool,
  });
  const MembershipCatalog = IDL.Record({
    'pro' : MembershipPricing,
    'enterprise' : MembershipPricing,
    'lastUpdated' : IDL.Int,
    'basic' : MembershipPricing,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeDeal' : IDL.Func([IDL.Text], [DealAnalysis], []),
    'assignBuyerToDeal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBuyer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createDeal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createDealFromAnalysis' : IDL.Func(
        [DealAnalysis, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBuyer' : IDL.Func([IDL.Nat], [], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [], []),
    'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getBuyer' : IDL.Func([IDL.Nat], [IDL.Opt(Buyer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(ContractDocument)], ['query']),
    'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
    'getMembershipCatalog' : IDL.Func([], [MembershipCatalog], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBuyers' : IDL.Func([], [IDL.Vec(Buyer)], ['query']),
    'listContractsByDeal' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ContractDocument)],
        ['query'],
      ),
    'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'moveDealToStage' : IDL.Func([IDL.Nat, DealStage], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBuyer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateContractStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'Unsigned' : IDL.Null, 'Signed' : IDL.Null }),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateDeal' : IDL.Func(
        [
          IDL.Nat,
          DealStage,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateMembershipPricing' : IDL.Func(
        [MembershipPricing, MembershipPricing, MembershipPricing],
        [],
        [],
      ),
    'updateMembershipTier' : IDL.Func([IDL.Principal, MembershipTier], [], []),
    'uploadContract' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'PurchaseContract' : IDL.Null,
            'AssignmentContract' : IDL.Null,
          }),
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };