/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AnalyticsData {
    closeRate: number;
    averageAssignmentFee: number;
    dealConversionPercent: number;
    monthlyRevenue: bigint;
    leadToContractPercent: number;
    profitByZipCode: Array<[string, bigint]>;
}
export interface MembershipPricing {
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    salePriceCents?: bigint;
    isOnSale: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MembershipCatalog {
    pro: MembershipPricing;
    enterprise: MembershipPricing;
    lastUpdated: bigint;
    basic: MembershipPricing;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Buyer {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    notes: string;
    propertyTypePreference: string;
    phone: string;
    budgetMax: bigint;
    budgetMin: bigint;
    preferredAreas: Array<string>;
}
export interface DealAnalysis {
    suggestedOfferPrice: bigint;
    estimatedARV: bigint;
    estimatedMAO: bigint;
    lastSoldPrice?: bigint;
    estimatedAssignmentFee: bigint;
    dealRating: Variant_A_B_C_Risky;
    address: string;
    comparableSales: Array<ComparableSale>;
    estimatedRehabCost: bigint;
}
export interface ComparableSale {
    distance: number;
    soldPrice: bigint;
    address: string;
    soldDate: bigint;
}
export interface Deal {
    id: bigint;
    arv: bigint;
    contractDeadline?: bigint;
    sellerPhone: string;
    owner: Principal;
    askingPrice: bigint;
    createdAt: bigint;
    actualProfit?: bigint;
    sellerName: string;
    updatedAt: bigint;
    stage: DealStage;
    address: string;
    notes: string;
    repairs: bigint;
    yourOffer: bigint;
    estimatedProfit: bigint;
    assignedBuyer?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
    membershipTier: MembershipTier;
}
export interface ContractDocument {
    id: bigint;
    emd?: bigint;
    documentType: Variant_PurchaseContract_AssignmentContract;
    owner: Principal;
    blob: ExternalBlob;
    fileName: string;
    dealId: bigint;
    closingDate?: bigint;
    signingStatus: Variant_Unsigned_Signed;
    uploadedAt: bigint;
}
export enum DealStage {
    Closed = "Closed",
    ContactedSeller = "ContactedSeller",
    UnderContract = "UnderContract",
    NewLead = "NewLead",
    Negotiating = "Negotiating",
    Assigned = "Assigned"
}
export enum MembershipTier {
    Pro = "Pro",
    Enterprise = "Enterprise",
    Basic = "Basic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_A_B_C_Risky {
    A = "A",
    B = "B",
    C = "C",
    Risky = "Risky"
}
export enum Variant_PurchaseContract_AssignmentContract {
    PurchaseContract = "PurchaseContract",
    AssignmentContract = "AssignmentContract"
}
export enum Variant_Unsigned_Signed {
    Unsigned = "Unsigned",
    Signed = "Signed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    analyzeDeal(address: string): Promise<DealAnalysis>;
    assignBuyerToDeal(dealId: bigint, buyerId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBuyer(name: string, phone: string, email: string, preferredAreas: Array<string>, budgetMin: bigint, budgetMax: bigint, propertyTypePreference: string, notes: string): Promise<bigint>;
    createDeal(sellerName: string, sellerPhone: string, address: string, arv: bigint, repairs: bigint, askingPrice: bigint, yourOffer: bigint, notes: string, estimatedProfit: bigint): Promise<bigint>;
    createDealFromAnalysis(analysis: DealAnalysis, sellerName: string, sellerPhone: string): Promise<bigint>;
    deleteBuyer(buyerId: bigint): Promise<void>;
    deleteDeal(dealId: bigint): Promise<void>;
    getAnalytics(): Promise<AnalyticsData>;
    getBuyer(buyerId: bigint): Promise<Buyer | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContract(contractId: bigint): Promise<ContractDocument | null>;
    getDeal(dealId: bigint): Promise<Deal | null>;
    getMembershipCatalog(): Promise<MembershipCatalog>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listBuyers(): Promise<Array<Buyer>>;
    listContractsByDeal(dealId: bigint): Promise<Array<ContractDocument>>;
    listDeals(): Promise<Array<Deal>>;
    moveDealToStage(dealId: bigint, newStage: DealStage): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBuyer(buyerId: bigint, name: string, phone: string, email: string, preferredAreas: Array<string>, budgetMin: bigint, budgetMax: bigint, propertyTypePreference: string, notes: string): Promise<void>;
    updateContractStatus(contractId: bigint, signingStatus: Variant_Unsigned_Signed, closingDate: bigint | null, emd: bigint | null): Promise<void>;
    updateDeal(dealId: bigint, stage: DealStage, sellerName: string, sellerPhone: string, address: string, arv: bigint, repairs: bigint, askingPrice: bigint, yourOffer: bigint, assignedBuyer: bigint | null, contractDeadline: bigint | null, notes: string, estimatedProfit: bigint, actualProfit: bigint | null): Promise<void>;
    updateMembershipPricing(basic: MembershipPricing, pro: MembershipPricing, enterprise: MembershipPricing): Promise<void>;
    updateMembershipTier(userId: Principal, tier: MembershipTier): Promise<void>;
    uploadContract(dealId: bigint, documentType: Variant_PurchaseContract_AssignmentContract, fileName: string, closingDate: bigint | null, emd: bigint | null, blob: ExternalBlob): Promise<bigint>;
}
import type { Buyer as _Buyer, ComparableSale as _ComparableSale, ContractDocument as _ContractDocument, Deal as _Deal, DealAnalysis as _DealAnalysis, DealStage as _DealStage, ExternalBlob as _ExternalBlob, MembershipCatalog as _MembershipCatalog, MembershipPricing as _MembershipPricing, MembershipTier as _MembershipTier, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async analyzeDeal(arg0: string): Promise<DealAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeDeal(arg0);
                return from_candid_DealAnalysis_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeDeal(arg0);
            return from_candid_DealAnalysis_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignBuyerToDeal(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBuyerToDeal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBuyerToDeal(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBuyer(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: bigint, arg5: bigint, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuyer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuyer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createDeal(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: string, arg8: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createDealFromAnalysis(arg0: DealAnalysis, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDealFromAnalysis(to_candid_DealAnalysis_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDealFromAnalysis(to_candid_DealAnalysis_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async deleteBuyer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBuyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBuyer(arg0);
            return result;
        }
    }
    async deleteDeal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeal(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getBuyer(arg0: bigint): Promise<Buyer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyer(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyer(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<ContractDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeal(arg0: bigint): Promise<Deal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeal(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeal(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipCatalog(): Promise<MembershipCatalog> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipCatalog();
                return from_candid_MembershipCatalog_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipCatalog();
            return from_candid_MembershipCatalog_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBuyers(): Promise<Array<Buyer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBuyers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBuyers();
            return result;
        }
    }
    async listContractsByDeal(arg0: bigint): Promise<Array<ContractDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContractsByDeal(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContractsByDeal(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeals();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeals();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveDealToStage(arg0: bigint, arg1: DealStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveDealToStage(arg0, to_candid_DealStage_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveDealToStage(arg0, to_candid_DealStage_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBuyer(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: bigint, arg6: bigint, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBuyer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBuyer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateContractStatus(arg0: bigint, arg1: Variant_Unsigned_Signed, arg2: bigint | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContractStatus(arg0, to_candid_variant_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContractStatus(arg0, to_candid_variant_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateDeal(arg0: bigint, arg1: DealStage, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint | null, arg10: bigint | null, arg11: string, arg12: bigint, arg13: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, to_candid_DealStage_n42(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg13));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, to_candid_DealStage_n42(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg10), arg11, arg12, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg13));
            return result;
        }
    }
    async updateMembershipPricing(arg0: MembershipPricing, arg1: MembershipPricing, arg2: MembershipPricing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipPricing(to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg0), to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg1), to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipPricing(to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg0), to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg1), to_candid_MembershipPricing_n51(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMembershipTier(arg0: Principal, arg1: MembershipTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipTier(arg0, to_candid_MembershipTier_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipTier(arg0, to_candid_MembershipTier_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadContract(arg0: bigint, arg1: Variant_PurchaseContract_AssignmentContract, arg2: string, arg3: bigint | null, arg4: bigint | null, arg5: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadContract(arg0, to_candid_variant_n53(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n54(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadContract(arg0, to_candid_variant_n53(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n54(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
async function from_candid_ContractDocument_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractDocument): Promise<ContractDocument> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DealAnalysis_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealAnalysis): DealAnalysis {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DealStage_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStage): DealStage {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MembershipCatalog_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipCatalog): MembershipCatalog {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipPricing_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipPricing): MembershipPricing {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipTier_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipTier): MembershipTier {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Buyer]): Buyer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContractDocument]): Promise<ContractDocument | null> {
    return value.length === 0 ? null : await from_candid_ContractDocument_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Deal]): Deal | null {
    return value.length === 0 ? null : from_candid_Deal_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone: string;
    membershipTier: _MembershipTier;
}): {
    name: string;
    email: string;
    phone: string;
    membershipTier: MembershipTier;
} {
    return {
        name: value.name,
        email: value.email,
        phone: value.phone,
        membershipTier: from_candid_MembershipTier_n20(_uploadFile, _downloadFile, value.membershipTier)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    emd: [] | [bigint];
    documentType: {
        PurchaseContract: null;
    } | {
        AssignmentContract: null;
    };
    owner: Principal;
    blob: _ExternalBlob;
    fileName: string;
    dealId: bigint;
    closingDate: [] | [bigint];
    signingStatus: {
        Unsigned: null;
    } | {
        Signed: null;
    };
    uploadedAt: bigint;
}): Promise<{
    id: bigint;
    emd?: bigint;
    documentType: Variant_PurchaseContract_AssignmentContract;
    owner: Principal;
    blob: ExternalBlob;
    fileName: string;
    dealId: bigint;
    closingDate?: bigint;
    signingStatus: Variant_Unsigned_Signed;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        emd: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.emd)),
        documentType: from_candid_variant_n27(_uploadFile, _downloadFile, value.documentType),
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName,
        dealId: value.dealId,
        closingDate: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.closingDate)),
        signingStatus: from_candid_variant_n30(_uploadFile, _downloadFile, value.signingStatus),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    arv: bigint;
    contractDeadline: [] | [bigint];
    sellerPhone: string;
    owner: Principal;
    askingPrice: bigint;
    createdAt: bigint;
    actualProfit: [] | [bigint];
    sellerName: string;
    updatedAt: bigint;
    stage: _DealStage;
    address: string;
    notes: string;
    repairs: bigint;
    yourOffer: bigint;
    estimatedProfit: bigint;
    assignedBuyer: [] | [bigint];
}): {
    id: bigint;
    arv: bigint;
    contractDeadline?: bigint;
    sellerPhone: string;
    owner: Principal;
    askingPrice: bigint;
    createdAt: bigint;
    actualProfit?: bigint;
    sellerName: string;
    updatedAt: bigint;
    stage: DealStage;
    address: string;
    notes: string;
    repairs: bigint;
    yourOffer: bigint;
    estimatedProfit: bigint;
    assignedBuyer?: bigint;
} {
    return {
        id: value.id,
        arv: value.arv,
        contractDeadline: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.contractDeadline)),
        sellerPhone: value.sellerPhone,
        owner: value.owner,
        askingPrice: value.askingPrice,
        createdAt: value.createdAt,
        actualProfit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.actualProfit)),
        sellerName: value.sellerName,
        updatedAt: value.updatedAt,
        stage: from_candid_DealStage_n34(_uploadFile, _downloadFile, value.stage),
        address: value.address,
        notes: value.notes,
        repairs: value.repairs,
        yourOffer: value.yourOffer,
        estimatedProfit: value.estimatedProfit,
        assignedBuyer: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedBuyer))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: _MembershipPricing;
    enterprise: _MembershipPricing;
    lastUpdated: bigint;
    basic: _MembershipPricing;
}): {
    pro: MembershipPricing;
    enterprise: MembershipPricing;
    lastUpdated: bigint;
    basic: MembershipPricing;
} {
    return {
        pro: from_candid_MembershipPricing_n38(_uploadFile, _downloadFile, value.pro),
        enterprise: from_candid_MembershipPricing_n38(_uploadFile, _downloadFile, value.enterprise),
        lastUpdated: value.lastUpdated,
        basic: from_candid_MembershipPricing_n38(_uploadFile, _downloadFile, value.basic)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    salePriceCents: [] | [bigint];
    isOnSale: boolean;
}): {
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    salePriceCents?: bigint;
    isOnSale: boolean;
} {
    return {
        annualPriceCents: value.annualPriceCents,
        monthlyPriceCents: value.monthlyPriceCents,
        salePriceCents: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.salePriceCents)),
        isOnSale: value.isOnSale
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestedOfferPrice: bigint;
    estimatedARV: bigint;
    estimatedMAO: bigint;
    lastSoldPrice: [] | [bigint];
    estimatedAssignmentFee: bigint;
    dealRating: {
        A: null;
    } | {
        B: null;
    } | {
        C: null;
    } | {
        Risky: null;
    };
    address: string;
    comparableSales: Array<_ComparableSale>;
    estimatedRehabCost: bigint;
}): {
    suggestedOfferPrice: bigint;
    estimatedARV: bigint;
    estimatedMAO: bigint;
    lastSoldPrice?: bigint;
    estimatedAssignmentFee: bigint;
    dealRating: Variant_A_B_C_Risky;
    address: string;
    comparableSales: Array<ComparableSale>;
    estimatedRehabCost: bigint;
} {
    return {
        suggestedOfferPrice: value.suggestedOfferPrice,
        estimatedARV: value.estimatedARV,
        estimatedMAO: value.estimatedMAO,
        lastSoldPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastSoldPrice)),
        estimatedAssignmentFee: value.estimatedAssignmentFee,
        dealRating: from_candid_variant_n10(_uploadFile, _downloadFile, value.dealRating),
        address: value.address,
        comparableSales: value.comparableSales,
        estimatedRehabCost: value.estimatedRehabCost
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    Risky: null;
}): Variant_A_B_C_Risky {
    return "A" in value ? Variant_A_B_C_Risky.A : "B" in value ? Variant_A_B_C_Risky.B : "C" in value ? Variant_A_B_C_Risky.C : "Risky" in value ? Variant_A_B_C_Risky.Risky : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    Enterprise: null;
} | {
    Basic: null;
}): MembershipTier {
    return "Pro" in value ? MembershipTier.Pro : "Enterprise" in value ? MembershipTier.Enterprise : "Basic" in value ? MembershipTier.Basic : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PurchaseContract: null;
} | {
    AssignmentContract: null;
}): Variant_PurchaseContract_AssignmentContract {
    return "PurchaseContract" in value ? Variant_PurchaseContract_AssignmentContract.PurchaseContract : "AssignmentContract" in value ? Variant_PurchaseContract_AssignmentContract.AssignmentContract : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Unsigned: null;
} | {
    Signed: null;
}): Variant_Unsigned_Signed {
    return "Unsigned" in value ? Variant_Unsigned_Signed.Unsigned : "Signed" in value ? Variant_Unsigned_Signed.Signed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Closed: null;
} | {
    ContactedSeller: null;
} | {
    UnderContract: null;
} | {
    NewLead: null;
} | {
    Negotiating: null;
} | {
    Assigned: null;
}): DealStage {
    return "Closed" in value ? DealStage.Closed : "ContactedSeller" in value ? DealStage.ContactedSeller : "UnderContract" in value ? DealStage.UnderContract : "NewLead" in value ? DealStage.NewLead : "Negotiating" in value ? DealStage.Negotiating : "Assigned" in value ? DealStage.Assigned : value;
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContractDocument>): Promise<Array<ContractDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ContractDocument_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n32(_uploadFile, _downloadFile, x));
}
function to_candid_DealAnalysis_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealAnalysis): _DealAnalysis {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_DealStage_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): _DealStage {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MembershipPricing_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipPricing): _MembershipPricing {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipTier_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): _MembershipTier {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suggestedOfferPrice: bigint;
    estimatedARV: bigint;
    estimatedMAO: bigint;
    lastSoldPrice?: bigint;
    estimatedAssignmentFee: bigint;
    dealRating: Variant_A_B_C_Risky;
    address: string;
    comparableSales: Array<ComparableSale>;
    estimatedRehabCost: bigint;
}): {
    suggestedOfferPrice: bigint;
    estimatedARV: bigint;
    estimatedMAO: bigint;
    lastSoldPrice: [] | [bigint];
    estimatedAssignmentFee: bigint;
    dealRating: {
        A: null;
    } | {
        B: null;
    } | {
        C: null;
    } | {
        Risky: null;
    };
    address: string;
    comparableSales: Array<_ComparableSale>;
    estimatedRehabCost: bigint;
} {
    return {
        suggestedOfferPrice: value.suggestedOfferPrice,
        estimatedARV: value.estimatedARV,
        estimatedMAO: value.estimatedMAO,
        lastSoldPrice: value.lastSoldPrice ? candid_some(value.lastSoldPrice) : candid_none(),
        estimatedAssignmentFee: value.estimatedAssignmentFee,
        dealRating: to_candid_variant_n15(_uploadFile, _downloadFile, value.dealRating),
        address: value.address,
        comparableSales: value.comparableSales,
        estimatedRehabCost: value.estimatedRehabCost
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    phone: string;
    membershipTier: MembershipTier;
}): {
    name: string;
    email: string;
    phone: string;
    membershipTier: _MembershipTier;
} {
    return {
        name: value.name,
        email: value.email,
        phone: value.phone,
        membershipTier: to_candid_MembershipTier_n46(_uploadFile, _downloadFile, value.membershipTier)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    salePriceCents?: bigint;
    isOnSale: boolean;
}): {
    annualPriceCents: bigint;
    monthlyPriceCents: bigint;
    salePriceCents: [] | [bigint];
    isOnSale: boolean;
} {
    return {
        annualPriceCents: value.annualPriceCents,
        monthlyPriceCents: value.monthlyPriceCents,
        salePriceCents: value.salePriceCents ? candid_some(value.salePriceCents) : candid_none(),
        isOnSale: value.isOnSale
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_A_B_C_Risky): {
    A: null;
} | {
    B: null;
} | {
    C: null;
} | {
    Risky: null;
} {
    return value == Variant_A_B_C_Risky.A ? {
        A: null
    } : value == Variant_A_B_C_Risky.B ? {
        B: null
    } : value == Variant_A_B_C_Risky.C ? {
        C: null
    } : value == Variant_A_B_C_Risky.Risky ? {
        Risky: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): {
    Closed: null;
} | {
    ContactedSeller: null;
} | {
    UnderContract: null;
} | {
    NewLead: null;
} | {
    Negotiating: null;
} | {
    Assigned: null;
} {
    return value == DealStage.Closed ? {
        Closed: null
    } : value == DealStage.ContactedSeller ? {
        ContactedSeller: null
    } : value == DealStage.UnderContract ? {
        UnderContract: null
    } : value == DealStage.NewLead ? {
        NewLead: null
    } : value == DealStage.Negotiating ? {
        Negotiating: null
    } : value == DealStage.Assigned ? {
        Assigned: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): {
    Pro: null;
} | {
    Enterprise: null;
} | {
    Basic: null;
} {
    return value == MembershipTier.Pro ? {
        Pro: null
    } : value == MembershipTier.Enterprise ? {
        Enterprise: null
    } : value == MembershipTier.Basic ? {
        Basic: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_Unsigned_Signed): {
    Unsigned: null;
} | {
    Signed: null;
} {
    return value == Variant_Unsigned_Signed.Unsigned ? {
        Unsigned: null
    } : value == Variant_Unsigned_Signed.Signed ? {
        Signed: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_PurchaseContract_AssignmentContract): {
    PurchaseContract: null;
} | {
    AssignmentContract: null;
} {
    return value == Variant_PurchaseContract_AssignmentContract.PurchaseContract ? {
        PurchaseContract: null
    } : value == Variant_PurchaseContract_AssignmentContract.AssignmentContract ? {
        AssignmentContract: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
